version: "3.8"

services:

  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #
  #                                                        #
  # Dataset Handlers                                       #
  #                                                        #
  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #

  # BIOM form handler
  biom-handler:
    container_name: user-dataset-biom-handler
    build:
      context: ./dataset-handlers/biom
      dockerfile: Dockerfile
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - internal


  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #
  #                                                        #
  # Import Service                                         #
  #                                                        #
  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #

  # Datastore
  postgres:
    container_name: user-dataset-import-datastore
    build:
      context: .
      dockerfile: ./pgDockerfile
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=1234
    networks:
      - internal

  # Import Service
  importer:
    container_name: user-dataset-import-service
    image: veupathdb/user-dataset-import-service
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - internal
      # - traefik
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - biom-handler
    environment:
      # iRODS Connection Info
      IRODS_HOST:
      IRODS_PORT:
      IRODS_USER:
      IRODS_PASS:
      IRODS_ZONE:
      IRODS_RESOURCE:

      # User token salt
      AUTH_SECRET_KEY:

      # Account DB Connection Info
      ACCT_DB_HOST:
      ACCT_DB_USER:
      ACCT_DB_PASS:
      ACCT_DB_NAME:
    labels:
      - "traefik.http.routers.dataset-import-service-dev.rule=Host(`dataset-import-service-dev.local.apidb.org`)"
      - "traefik.http.routers.dataset-import-service-dev.tls=true"
      - "traefik.http.routers.dataset-import-service-dev.entrypoints=local"
      - "traefik.http.services.dataset-import-service-dev.loadbalancer.server.port=80"


volumes:
  pg-data:

networks:
  internal:
    external: false
  # traefik:
    # external: true